### ISSUE TITLE
Changing parameter quarkus.datasource.jdbc.url in application.properties doesn't have any effect

### ISSUE THREAD

**Issue by FrankBergemann** [cescoffier/quarkus-todo-app#24]
I want to run quarkus-todo-app and postgres DB in separate containers in a container network using `docker-compose up` cmd.
To make this work I made the following change in application.properties file:
`quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/rest-crud`
-->
`quarkus.datasource.jdbc.url=jdbc:postgresql://db_1/rest-crud`
The change is hinted in the following post: https://github.com/prisma/prisma/issues/1385#issuecomment-576695684
However, this change doesn't have any effect. Running `docker-compose up` the error messages show that the todo-app is still trying to connect to the DB on localhost:

```
db_1                    | 2021-04-21 06:51:21.202 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                    | 2021-04-21 06:51:21.202 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1                    | 2021-04-21 06:51:21.208 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                    | 2021-04-21 06:51:21.215 UTC [75] LOG:  database system was shut down at 2021-04-21 06:51:21 UTC
db_1                    | 2021-04-21 06:51:21.222 UTC [1] LOG:  database system is ready to accept connections
quarkus-todo-backend_1  | __  ____  __  _____   ___  __ ____  ______
quarkus-todo-backend_1  |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
quarkus-todo-backend_1  |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
quarkus-todo-backend_1  | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
quarkus-todo-backend_1  | 2021-04-21 06:51:24,668 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections w
ill be created when necessary
quarkus-todo-backend_1  | 2021-04-21 06:51:24,907 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. C
heck that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
quarkus-todo-backend_1  | 2021-04-21 06:51:24,908 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (main) HHH000342: Could not obtain con
nection to query metadata: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct
and that the postmaster is accepting TCP/IP connections.
quarkus-todo-backend_1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
quarkus-todo-backend_1  |       at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
quarkus-todo-backend_1  |       at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
quarkus-todo-backend_1  |       at org.postgresql.Driver.makeConnection(Driver.java:465)
quarkus-todo-backend_1  |       at org.postgresql.Driver.connect(Driver.java:264)
quarkus-todo-backend_1  |       at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
quarkus-todo-backend_1  |       at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:452)
quarkus-todo-backend_1  |       at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:434)
quarkus-todo-backend_1  |       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
quarkus-todo-backend_1  |       at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
```
Can it be that the code is using hard-coded values instead of the config setting? I wonder also why there is a way to change DB port 5432. For example by setting `quarkus.datasource.jdbc.url=jdbc:postgresql://<host>:<port-number>/rest-crud`.  But port 5432 seems to be hard-coded as well.

**Comment by cescoffier** [comment]
Check https://quarkus.io/guides/datasource

Configuration should be:
```
quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=<your username>
quarkus.datasource.password=<your password>

quarkus.datasource.jdbc.url=jdbc:postgresql://docker-service-name:5432/database
quarkus.datasource.jdbc.max-size=16
```

Verify that there is not a prod profile enabled too.

**Comment by FrankBergemann** [comment]
My full application.properties file looks like this:
```
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=restcrud
quarkus.datasource.password=restcrud
quarkus.datasource.jdbc.url=jdbc:postgresql://db_1:5432/rest-crud
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.jdbc.min-size=2
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
```
However, I'm still getting the same error mesage as posted above:

```
db_1                    | 2021-04-25 16:08:30.608 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                    | 2021-04-25 16:08:30.616 UTC [73] LOG:  database system was shut down at 2021-04-25 16:08:30 UTC
db_1                    | 2021-04-25 16:08:30.623 UTC [1] LOG:  database system is ready to accept connections
quarkus-todo-backend_1  | __  ____  __  _____   ___  __ ____  ______
quarkus-todo-backend_1  |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
quarkus-todo-backend_1  |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
quarkus-todo-backend_1  | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
quarkus-todo-backend_1  | 2021-04-25 16:08:33,985 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
quarkus-todo-backend_1  | 2021-04-25 16:08:34,124 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that
the postmaster is accepting TCP/IP connections.
quarkus-todo-backend_1  | 2021-04-25 16:08:34,126 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (main) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLEx
ception: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```
In the meeages above you see `Datasource '<default>':`. Is this correct?
Do I understand the documentation in  https://quarkus.io/guides/datasource correctly, that I don't need to install any extensions via these maven commands:
./mvnw quarkus:add-extension -Dextensions="agroal"
./mvnw quarkus:add-extension -Dextensions="jdbc-postgresql"
because its all included in the pom file?
These comands fail 
```
$ ./mvnw quarkus:add-extension -Dextensions="agroal"
curl: (3) URL using bad/illegal format or missing URL
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```
Any further Ideas? I used th quarkus-todo directory of your project.

**Comment by cescoffier** [comment]
Can you provide a full reproducer. It looks weird.
And no, you don’t have to install any other extension, and the error you
have is about the maven wrapper not being available.

**Comment by FrankBergemann** [comment]
Hi Clement,
I created a githup repo with a full reproducer of the issue: https://github.com/FrankBergemann/quarkus-todo-postgres-DB-issue
Please see README.md file on steps to reproduce the error.
-- Frank

**Comment by cescoffier** [comment]
Just use quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/rest-crud, and not the _1 suffix. IF you have multiple DB, use a proper link (and avoid that suffix).

Do NOT forget to rebuild EVERY TIME you change the value:
```
docker compose up --build
```

**Comment by FrankBergemann** [comment]
Hi Clement,
With your suggestions, it's working now. I didn't know the fine details.
Thank you very much :-) Ticket closed.
